### ISSUE TITLE
package.json path error

### ISSUE THREAD

**Issue by lamontacrook** [adobe/aem-react-core-wcm-components-examples#1]
There is an incorrect path in the [package.json](https://github.com/adobe/aem-react-core-wcm-components-examples/blob/master/react-webcomponents-example-project/package.json) scripts.  The clientlibs directory should be `../ui.apps/src/main/content/jcr_root/apps/core-components-examples/wcm-react/clientlibs/react-webcomponents/resources` and not `../ui.apps/src/content/jcr_root/apps/core-components-examples/wcm-react/clientlibs/react-webcomponents/resources`.  This error prevents the REACT components from getting built into clientlibs.

**Comment by niekraaijmakers** [comment]
Fixed. Thanks!
